spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wbx1998


mybatis:
  mapper-locations: classpath:mappers/*.xml
